### ISSUE TITLE
question for the project

### ISSUE THREAD

**Issue by lebaleser** [gfcwfzkm/SMARTREXE_displayDriver#1]
Hello!I have a question about this project. I have a display on the st7586 controller from buydisplay (240x160 pixels). When displaying characters size=1 (5x8), one vertical column is lost (I counted the third one) and characters are output without a space between them (the character size is 4x7). The font size changes in multiples of 6 pixels, but the font of the second size does not have a 12x16 matrix, the height (16) is correct, and the width is only 7 pixels per character. It is good that a space of 1 pixel appears in this case. Can you give me some advice on this little problem? 
My e-mail : las255@yandex.ru

Best regards, lebaleser

**Comment by gfcwfzkm** [comment]
Hmm, good question. Maybe something with the initialisation needs to be changed for your size of display, which seems smaller in width but larger in height. Do you have a link of your buydisplay display?

**Comment by lebaleser** [comment]
Thanks for your attention. Here's the link to my display :  https://www.buydisplay.com/3-4-inch-240x160-dot-matrix-lcd-display-serial-interface-black-on-white
 In initialization, I changed only the size of Y (160) - the indication is up to the bottom.
I only used monochrome mode (i haven't tried brightness gradations yet).

**Comment by gfcwfzkm** [comment]
The X and Y size in the defines isn't used for initialisation. The initialisation function is hard-coded for the Smartrexe device. You maybe need to change the initialisation function in my library with the init example code from buydisplay. Sadly I don't have a display to test it myself, else I'd test the changes and update the library.

**Comment by lebaleser** [comment]
This define not use? (in file st7586.h)
#define ST7586_DISPLAYSIZE_X	384        //
#define ST7586_DISPLAYSIZE_Y	160      //

**Comment by gfcwfzkm** [comment]
Nope it's not used, it's just a reference but it's not used in the library
Check `ST7586_init(char monochrome)` in ST7586.c, you need to adjust the initialisation with the example code one from buydisplay

**Comment by lebaleser** [comment]
I will try. There is initialization using the 0x2A and 0x2b commands (regarding the x and y dimensions).
Tnx
